export const Products = [
  {
    id: 1,
    name: "Apple",
    type: "Fruit",
    price: 120,
    delivery: "Free",
    offer: "10% Off",
    image: "https://www.heart.org/en/-/media/AHA/Recipe/Article-Images/Apples.jpg",
    quantity: "1 kg",
    alsoKnownAs: "Seb",
    seasonality: "Available year-round, best in winter.",
    basicInfo: "Apples are sweet, crunchy fruits enjoyed fresh or in cooked dishes.",
    health: "Rich in dietary fiber, Vitamin C, and antioxidants. Supports heart health and digestion.",
    speciality: "Eaten raw, in pies, juices, salads, or smoothies."
  },
  {
    id: 2,
    name: "Banana",
    type: "Fruit",
    price: 60,
    delivery: "Charged",
    offer: "No Offer",
    image: "https://nutritionsource.hsph.harvard.edu/wp-content/uploads/2018/08/bananas-1354785_1920.jpg",
    quantity: "1 dozen",
    alsoKnownAs: "Kela",
    seasonality: "Available all year round.",
    basicInfo: "Bananas are soft, sweet tropical fruits with a creamy texture.",
    health: "Excellent source of potassium, Vitamin B6, and fiber. Helps maintain energy and supports digestion.",
    speciality: "Used in shakes, desserts, snacks, and baked goods."
  },
  {
    id: 3,
    name: "Tomato",
    type: "Vegetable",
    price: 40,
    delivery: "Free",
    offer: "5% Off",
    image: "https://media.post.rvohealth.io/wp-content/uploads/2020/09/AN313-Tomatoes-732x549-Thumb.jpg",
    quantity: "1 KG",
    alsoKnownAs: "Tamatar",
    seasonality: "Available year-round, peak in summer.",
    basicInfo: "Tomatoes are juicy, tangy fruits often used as vegetables in cooking.",
    health: "Rich in Vitamin C, potassium, folate, and antioxidants like lycopene.",
    speciality: "Essential for curries, salads, sauces, soups, and juices."
  },
  {
    id: 4,
    name: "Potato",
    type: "Vegetable",
    price: 35,
    delivery: "Free",
    offer: "No Offer",
    image: "https://www.forksoverknives.com/uploads/2025/03/new-potatoes-featured-image.jpg",
    quantity: "1 kg",
    alsoKnownAs: "Aloo",
    seasonality: "Available year-round.",
    basicInfo: "Potatoes are starchy tubers widely consumed worldwide.",
    health: "Good source of carbohydrates, potassium, and Vitamin C. Provides quick energy.",
    speciality: "Used in fries, chips, curries, snacks, and baked dishes."
  },
  {
    id: 5,
    name: "Lady Finger (Bhindi)",
    type: "Vegetable",
    price: 40,
    delivery: "Free",
    offer: "5% Off",
    image: "https://5.imimg.com/data5/SELLER/Default/2022/6/IX/CW/FY/31131351/all-you-need-to-know-about-okra-health-benefits-jpg-500x500.jpg",
    quantity: "1 kg",
    alsoKnownAs: "Okra, Bhindi",
    seasonality: "Available year-round, best in summer and monsoon.",
    basicInfo: "Lady finger is a green, slender vegetable with a mild flavor and sticky texture when cut.",
    health: "Low in calories, rich in fiber, Vitamin C, and folate. Supports digestion and blood sugar control.",
    speciality: "Commonly stir-fried, curried, or used in soups and stews."
  }
];
